{
  "title": "101intentional_error",
  "description": "The example tests intentionally made error which breaks the task execution.",
  "category": "examples",
  "thumbnail": "",
  "output_response": false,
  "environment": "nodejs"
}